name: do-apps-rust-example
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: zenozaga/do-apps-rust-example-db
  name: do-apps-rust-example
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
